{% set name = "apache-beam" %}
{% set version = "2.45.0" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: 7fed999def2e4e3bb9a062045249ee02eec97caf8293a9ecbe73e1812fa241d2
  patches:
    - 0001-fix-osx-protobuf.patch

build:
  skip: true  # [win or py>=311]
  number: 0

requirements:
  host:
    - python
    - numpy >=1.14.3,<1.23.0
    - cython >=0.28.1
  run:
    - python

outputs:
  - name: {{ name }}
    script: build_apache_beam.sh
    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - cython >=0.28.1                        # [build_platform != target_platform]
        - {{ compiler('c') }}
        - numpy >=1.14.3,<1.23.0                 # [build_platform != target_platform]
      host:
        - python
        - cython >=0.28.1
        - pip >=19.3.0
        - numpy >=1.14.3,<1.23.0
      run:
        - python
        - cython >=0.28.1
        - crcmod >=1.7,<2.0
        - dill >=0.3.1.1,<0.3.2
        - cloudpickle >=2.2.0,<2.3.0
        - fastavro >=0.23.6,<2
        - fasteners >=0.3,<1.0
        - grpcio >=1.33.1,!=1.48.0,<2
        - python-hdfs >=2.1.0,<3.0.0
        - httplib2 >=0.8,<0.20.0
        - numpy >=1.14.3,<1.23.0
        - objsize >=0.6.1,<0.7.0
        - orjson <4.0
        - protobuf >3.12.2,<4
        - proto-plus >=1.7.1,<2
        - pyarrow >=0.15.1,<10.0.0
        - pydot >=1.2.0,<2
        - python-dateutil >=2.8.0,<3
        - pymongo >=3.8.0,<4.0.0
        - pytz >=2018.3
        - regex >=2020.6.8
        - requests >=2.24.0,<3.0.0
        - typing-extensions >=3.7.0
        - zstandard >=0.18.0,<1

    test:
      requires:
        - pip
      imports:
        - apache_beam
        - apache_beam.coders
        - apache_beam.examples.complete.game
        - apache_beam.examples.complete.juliaset
        - apache_beam.examples.complete.juliaset.juliaset
        - apache_beam.examples.cookbook
        - apache_beam.examples.flink
        - apache_beam.examples.snippets
        - apache_beam.internal
        - apache_beam.internal.gcp
        - apache_beam.io
        - apache_beam.io.flink
        - apache_beam.io.gcp
        - apache_beam.io.gcp.datastore
        - apache_beam.io.gcp.internal
        - apache_beam.io.gcp.tests
        - apache_beam.metrics
        - apache_beam.options
        - apache_beam.portability
        - apache_beam.portability.api
        - apache_beam.runners
        - apache_beam.runners.dataflow
        - apache_beam.runners.direct
        - apache_beam.runners.interactive
        - apache_beam.runners.interactive.display
        - apache_beam.runners.job
        - apache_beam.runners.portability
        - apache_beam.runners.test
        - apache_beam.runners.worker
        - apache_beam.testing
        - apache_beam.testing.benchmarks
        - apache_beam.testing.benchmarks.nexmark
        - apache_beam.testing.benchmarks.nexmark.models
        - apache_beam.testing.benchmarks.nexmark.queries
        - apache_beam.tools
        - apache_beam.transforms
        - apache_beam.typehints
        - apache_beam.utils
      commands:
        - pip check

  - name: {{ name }}-with-gcp
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage(name, max_pin='x.x.x.x.x.x') }}
        # Try match what's in https://github.com/apache/beam/blob/v{{ version }}/sdks/python/setup.py#L268
        - cachetools >=3.1.0,<5
        - google-apitools >=0.5.31,<0.5.32
        - google-auth >=1.18.0,<2
        - google-auth-httplib2 >=0.1.0,<0.2.0
        - google-cloud-datastore >=1.8.0,<2
        - google-cloud-pubsub >=2.1.0,<3
        - google-cloud-pubsublite >=1.2.0,<2
        - google-cloud-bigquery-core >=1.6.0,<4
        - google-cloud-bigquery-storage >=2.6.3,<2.14
        - google-cloud-core >=0.28.1,<3
        - google-cloud-bigtable >=0.31.1,<2
        - google-cloud-spanner >=3.0.0,<4
        - google-cloud-dlp >=3.0.0,<4
        - google-cloud-language >=1.3.0,<2
        - google-cloud-videointelligence >=1.8.0,<2
        - google-cloud-vision >=2,<4
        - google-cloud-recommendations-ai >=0.1.0,<0.8.0
    test:
      imports:
        # not sure what test is useful...
        - apache_beam
      commands:
        - pip check
      requires:
        - pip

#  - name: {{ name }}-with-interactive
#    requirements:
#      host:
#        - python
#      run:
#        - python
#        - {{ pin_subpackage(name, max_pin='x.x.x.x.x.x') }}
#        - facets-overview >=1.0.0,<2
#        - google-cloud-dataproc >=3.0.0,<3.2.0
#        - ipython >=8,<9
#        - ipykernel >=6,<7
#        - ipywidgets >=8,<9
#        - jupyter_client >=6.1.11,<6.1.13
#        - timeloop >=1.0.2,<2
#    test:
#      imports:
#        # not sure what test is useful...
#        - apache_beam
#      commands:
#        - pip check
#      requires:
#        - pip

  - name: {{ name }}-with-aws
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage(name, max_pin='x.x.x.x.x.x') }}
        - boto3 >=1.9
    test:
      imports:
        # not sure what test is useful...
        - apache_beam
      commands:
        - pip check
      requires:
        - pip

  - name: {{ name }}-with-azure
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage(name, max_pin='x.x.x.x.x.x') }}
        - azure-storage-blob >=12.3.2
        - azure-core >=1.7.0
        - azure-identity >=1.12.0
    test:
      imports:
        # not sure what test is useful...
        - apache_beam
      commands:
        - pip check
      requires:
        - pip

  - name: {{ name }}-with-dataframe
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage(name, max_pin='x.x.x.x.x.x') }}
        - pandas >=1.0,<1.5  # [py<310]
        - pandas >=1.4.3,<1.5  # [py>=310]
    test:
      imports:
        # not sure what test is useful...
        - apache_beam
      commands:
        - pip check
      requires:
        - pip

  - name: {{ name }}-with-dask
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage(name, max_pin='x.x.x.x.x.x') }}
        - dask >=2022.6
        - distributed >=2022.6
    test:
      imports:
        # not sure what test is useful...
        - apache_beam
      commands:
        - pip check
      requires:
        - pip


about:
  home: https://beam.apache.org
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Apache Beam: An advanced unified programming model'

  description: |
    Apache Beam is an open source, unified model for defining both batch
    and streaming data-parallel processing pipelines. Using one of the open
    source Beam SDKs, you build a program that defines the pipeline. The
    pipeline is then executed by one of Beam’s supported distributed
    processing back-ends, which include Apache Apex, Apache Flink, Apache
    Spark, and Google Cloud Dataflow.
  doc_url: https://beam.apache.org/documentation/
  dev_url: https://github.com/apache/beam

extra:
  recipe-maintainers:
    - sodre
    - aaltay
    - xylar
